DATA_DIR = 'data_analysis/data'
YEARS = [2022, 2023, 2024]
HOUSEHOLD_COLS = ['SSUID', 'SHHADID', 'THTOTINC', 'SPANEL', 'SWAVE', 'MONTHCODE', 'RMESR', 'EJB1_JBORSE', 'EJB2_JBORSE']
MIN_MONTHS = 6
LARGE_JUMP_THRESHOLD = 0.30
SMALL_CHANGE_THRESHOLD = 0.05
NROWS = 10000